heartbeat.monitors:

#------------------------------- RabbitMQ Module -------------------------------
# - module: rabbitmq
#   enabled: true
#   metricsets: ["node"]
#   period: 5s
#   hosts: ["rabbitmq:15672"]
#   username: guest
#   password: guest

# #------------------------------- MySQL Module -------------------------------
# - module: mysql
#   enabled: true
#   metricsets: ["status"]
#   period: 5s
#   hosts: ["tcp(mysql:3306)/"]
#   username: root
#   password: root

# #------------------------------- MongoDB Module -------------------------------

# - module: mongodb
#   enabled: true
#   metricsets: ["status", "dbstats"]
#   period: 5s
#   hosts: ["mongodb:27017"]

#------------------------------- API Health Check -------------------------------
- type: http
  enabled: true
  schedule: '@every 30s'
  urls: ["https://ctrmapi.pttplc.com/smt_deal/LIVE"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200

# #------------------------------- Redis Module -------------------------------
# - module: redis
#   enabled: true
#   metricsets: ["info", "keyspace"]
#   period: 5s
#   hosts: ["redis:6379"]

# #------------------------------- Nginx Module -------------------------------
# - module: nginx
#   enabled: true
#   metricsets: ["stubstatus"]
#   period: 5s
#   hosts: ["http://nginx"]
#   server_status_path: "nginx_status"

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  
# setup.kibana:
#   host: "${HOST_KIBANA}"

#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag.
processors:
- add_docker_metadata: ~

monitoring.enabled: true


logging.to_files: false
